In [2]:
#include "stdio.h"
#include "stdlib.h"
#include <iostream>
#include <vector>

/*a workaround to solve cling issue*/
#include "../macos_cling_workaround.hpp"
/*set libtorch path, load libs*/
#include "../load_libtorch.hpp"
#include <torch/torch.h>

# 1.创建一个Tensor

创建未初始化的tensor：

In [2]:
torch::Tensor t1 = torch::empty(3, torch::kInt64);

std::cout << t1 << std::endl;

 1.3983e+14
 9.4067e+13
 6.8719e+10
[ CPULongType{3} ]


In [3]:
torch::Tensor t2 = torch::empty({5,6}, torch::kInt32);
std::cout << t2 << std::endl;

-5.7050e+08  2.1851e+04  0.0000e+00  0.0000e+00  9.0000e+00  1.2322e+09
 1.2634e+09  9.0921e+08  1.9531e+09  1.7687e+09  1.6013e+09  1.9537e+09
 8.7696e+08  1.7025e+09  1.9126e+09  1.5993e+09  1.6000e+02  0.0000e+00
 8.0000e+01  0.0000e+00 -5.6166e+08  2.1851e+04  0.0000e+00  0.0000e+00
 1.0000e+01  1.9524e+09  1.2634e+09  9.0921e+08  1.9531e+09  1.7687e+09
[ CPUIntType{5,6} ]


In [4]:
torch::Tensor t3 = torch::empty({3,4,2}, torch::kInt8);
std::cout << t3 << std::endl;

(1,.,.) = 
  101  102
  105  110
  101  100
   84  101

(2,.,.) = 
  110  115
  111  114
   73  109
  112  108

(3,.,.) = 
   69   69
   55  114
  101  116
   97  105
[ CPUCharType{3,4,2} ]


创建值为0的tensor：

In [5]:
torch::Tensor x = torch::zeros({3, 4});
std::cout << x << std::endl;

torch::Tensor y = torch::zeros({3, 4}, torch::kInt);
std::cout << y << std::endl;

 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUFloatType{3,4} ]
 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUIntType{3,4} ]


创建值为随机数的tensor：

In [6]:
torch::Tensor x = torch::rand({3, 4});
std::cout << x << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor y = torch::rand({3, 4}, torch::kFloat64);
std::cout << y << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor z = torch::randn({5, 3, 4}, torch::kFloat32);
std::cout << z << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 0.4444  0.7839  0.3972  0.5826
 0.8967  0.1082  0.5972  0.1979
 0.5112  0.3519  0.5890  0.8016
[ CPUFloatType{3,4} ]
<<<=========>>>

 0.3386  0.7420  0.4815  0.3888
 0.8127  0.1300  0.6292  0.4419
 0.7200  0.4255  0.8997  0.3681
[ CPUDoubleType{3,4} ]
<<<=========>>>

(1,.,.) = 
 -0.2787  1.2748  0.8307  0.9763
 -0.3594 -1.1021 -0.6364 -0.0364
  0.7180  0.0749 -0.0436 -2.4029

(2,.,.) = 
 -0.2440 -0.0459  0.8772 -0.9237
 -1.6146 -0.5144 -0.0731  0.2669
 -0.5208 -0.0864  0.9103  0.8287

(3,.,.) = 
 -0.8943 -1.7940  0.0125  1.6025
 -2.0548  0.3773  1.4870  0.5982
 -0.0344  0.8939  1.7970  0.5809

(4,.,.) = 
  1.1613 -1.6727 -1.1365  1.2555
 -0.1700  0.2928  1.7869 -0.2510
  0.2229  2.3172 -2.0089 -0.7028

(5,.,.) = 
 -0.1174 -0.4590 -0.6379  0.7281
  0.0454  0.5225 -0.3091  1.8815
  0.1755 -1.0258 -0.2639  0.5765
[ CPUFloatType{5,3,4} ]
<<<=========>>>



根据已有tensor创建新的tensor：

In [7]:
torch::Tensor t = torch::ones({3,3});
t += 2;


torch::Tensor a(t);
std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 3  3  3
 3  3  3
 3  3  3
[ CPUFloatType{3,3} ]
<<<=========>>>



In [8]:
torch::Tensor a = torch::ones({5,3});
a = torch::randn_like(a);

std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 0.1059  1.7008 -1.0940
 0.6755 -0.5386 -1.5082
 0.5866  0.4006  1.7089
-0.3359  0.1243 -0.2685
 1.2250 -1.8495  0.8217
[ CPUFloatType{5,3} ]
<<<=========>>>



更多例子请参考 [Tensor Creation API](https://pytorch.org/cppdocs/notes/tensor_creation.html)

# 2. Tensor的相关运算

## 加法运算

In [10]:
torch::Tensor x = torch::ones({5,3});
torch::Tensor y = torch::randn({5,3});

std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

std::cout << "y =" << std::endl;
std::cout << (y) << std::endl << std::endl;

std::cout << "x+y =" << std::endl;
std::cout << (x+y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "torch::add(x,y) =" << std::endl;
std::cout << torch::add(x,y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "y.add_(x) =" << std::endl;
std::cout << y.add_(x) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

x =
 1  1  1
 1  1  1
 1  1  1
 1  1  1
 1  1  1
[ CPUFloatType{5,3} ]

y =
-0.4262  0.2588 -1.2324
 1.5842 -1.4629  0.5925
-0.2029  0.6585 -0.0634
 2.2986 -0.6072  0.9584
 2.4718  1.3781  1.0643
[ CPUFloatType{5,3} ]

x+y =
 0.5738  1.2588 -0.2324
 2.5842 -0.4629  1.5925
 0.7971  1.6585  0.9366
 3.2986  0.3928  1.9584
 3.4718  2.3781  2.0643
[ CPUFloatType{5,3} ]
<<<=========>>>

torch::add(x,y) =
 0.5738  1.2588 -0.2324
 2.5842 -0.4629  1.5925
 0.7971  1.6585  0.9366
 3.2986  0.3928  1.9584
 3.4718  2.3781  2.0643
[ CPUFloatType{5,3} ]
<<<=========>>>

y.add_(x) =
 0.5738  1.2588 -0.2324
 2.5842 -0.4629  1.5925
 0.7971  1.6585  0.9366
 3.2986  0.3928  1.9584
 3.4718  2.3781  2.0643
[ CPUFloatType{5,3} ]
<<<=========>>>



## 索引
借助于torch::Tensor::index()和torch::Tensor::index_put_()函数，我们可以在libtorch中实现类似pytorch中对tensor的切片存取操作。具体说明详见[tensor_indexing](https://pytorch.org/cppdocs/notes/tensor_indexing.html)页面.

In [14]:
torch::Tensor x = torch::zeros(15);

for (int i = 0; i < 15; i++) {
    x[i] = i;
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

/* *
 *  Getter ops
 */
std::cout << "(in python) x[None]=" << std::endl;
std::cout << (x.index({torch::indexing::None})) << std::endl << std::endl;

std::cout << "(in python) x[Ellipsis, ...]=" << std::endl;
std::cout << (x.index({torch::indexing::Ellipsis, "..."})) << std::endl << std::endl;

std::cout << "(in python) x[7]=" << std::endl;
std::cout << (x.index({7})) << std::endl << std::endl;

std::cout << "(in python) x[True, False]=" << std::endl;
std::cout << (x.index({true,false,true,false,true,false,true,false,true,false,false,true,false,true,false})) << std::endl << std::endl;

std::cout << "(in python) x[1::2]=" << std::endl;
std::cout << (x.index({torch::indexing::Slice(1, torch::indexing::None, 2)})) << std::endl << std::endl;

std::cout << "(in python) x[::2]=" << std::endl;
std::cout << (x.index({torch::indexing::Slice(torch::indexing::None, torch::indexing::None, 2)})) << std::endl << std::endl;


x =
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
[ CPUFloatType{15} ]

(in python) x[None]=
  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14
[ CPUFloatType{1,15} ]

(in python) x[Ellipsis, ...]=
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
[ CPUFloatType{15} ]

(in python) x[7]=
7
[ CPUFloatType{} ]

(in python) x[True, False]=
[ CPUFloatType{0,15} ]

(in python) x[1::2]=
  1
  3
  5
  7
  9
 11
 13
[ CPUFloatType{7} ]

(in python) x[::2]=
  0
  2
  4
  6
  8
 10
 12
 14
[ CPUFloatType{8} ]



In [3]:
torch::Tensor x = torch::zeros(15);

for (int i = 0; i < 15; i++) {
    x[i] = i;
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

/* *
 *  Setter ops
 */
std::cout << "(in python) x[None] = 1" << std::endl;
std::cout << (x.index_put_({torch::indexing::None}, 1)) << std::endl << std::endl;

std::cout << "(in python) x[Ellipsis, ...] = 2" << std::endl;
std::cout << (x.index_put_({torch::indexing::Ellipsis, "..."}, 2)) << std::endl << std::endl;

std::cout << "(in python) x[7] = 3" << std::endl;
std::cout << (x.index_put_({7}, 3)) << std::endl << std::endl;

std::cout << "(in python) x[True, False] = 4" << std::endl;
std::cout << (x.index_put_({true,false,true,false,true,false,true,false,true,false,false,true,false,true,false}, 4)) << std::endl << std::endl;

std::cout << "(in python) x[1::2] = 5" << std::endl;
std::cout << (x.index_put_({torch::indexing::Slice(1, torch::indexing::None, 2)}, 5)) << std::endl << std::endl;

std::cout << "(in python) x[::2] = 6" << std::endl;
std::cout << (x.index_put_({torch::indexing::Slice(torch::indexing::None, torch::indexing::None, 2)}, 6)) << std::endl << std::endl;


x =
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
[ CPUFloatType{15} ]

(in python) x[None] = 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
[ CPUFloatType{15} ]

(in python) x[Ellipsis, ...] = 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
[ CPUFloatType{15} ]

(in python) x[7] = 3
 2
 2
 2
 2
 2
 2
 2
 3
 2
 2
 2
 2
 2
 2
 2
[ CPUFloatType{15} ]

(in python) x[True, False] = 4
 2
 2
 2
 2
 2
 2
 2
 3
 2
 2
 2
 2
 2
 2
 2
[ CPUFloatType{15} ]

(in python) x[1::2] = 5
 2
 5
 2
 5
 2
 5
 2
 5
 2
 5
 2
 5
 2
 5
 2
[ CPUFloatType{15} ]

(in python) x[::2] = 6
 6
 5
 6
 5
 6
 5
 6
 5
 6
 5
 6
 5
 6
 5
 6
[ CPUFloatType{15} ]



### Python 与 C++ 索引类型对照表

|Python | C++ (assuming using namespace torch::indexing) |
|:---|:---|
|None|None|
|Ellipsis|Ellipsis|
|...|"..."|
|123|123|
|True|true|
|False|false|
|: or ::|Slice() or Slice(None, None) or Slice(None, None, None)|
|1: or 1::|Slice(1, None) or Slice(1, None, None)|
|:3 or :3:|Slice(None, 3) or Slice(None, 3, None)|
|::2|Slice(None, None, 2)|
|1:3|Slice(1, 3)|
|1::2|Slice(1, None, 2)|
|:3:2|Slice(None, 3, 2)|
|1:3:2|Slice(1, 3, 2)|
|torch.tensor([1, 2])|torch::tensor({1, 2})|

### 其它索引操作

In [34]:
torch::Tensor x = torch::zeros({3,4});

for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 4; j++) {
        x[i][j] = i*4+j;
    }
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;


/** Warning:
 *  a known issue: with xeus-cling, if you call torch::from_blob,
 *  there will be a link error, 
 *  
 *  IncrementalExecutor::executeFunction: 
 *  symbol '__emutls_v._ZSt11__once_call' unresolved 
 *  while linking function '_GLOBAL__sub_I_cling_module_8'!
 *
 *
 *  so I write this example in pure 
 *  c++ code in folder : 'cpp_project/basic_ops'.
 */
// std::vector<int32_t> v = {1,2,7,8}; 
// auto idx = torch::from_blob(v.data(), v.size(), torch::kInt32);


std::cout << "<<< tensor.index_select >>>" << std::endl;
torch::Tensor idx = torch::arange(1,3);
std::cout << (idx) << std::endl << std::endl;

std::cout << "x.index_select(dim = 0, index = idx) =" << std::endl;
std::cout << (x.index_select(0,idx)) << std::endl << std::endl;

std::cout << "x.index_select(dim = 1, index = idx) =" << std::endl;
std::cout << (x.index_select(1,idx)) << std::endl << std::endl;


std::cout << "<<< tensor.masked_select >>>" << std::endl;
torch::Tensor mask = x > 5;
std::cout << (mask) << std::endl << std::endl;
std::cout << "x.masked_select(mask = mask) =" << std::endl;
std::cout << (x.masked_select(mask)) << std::endl << std::endl;

std::cout << "<<< tensor.nonzero >>>" << std::endl;
std::cout << "注意，返回值是非零元素下标，即x,y "<< std::endl << "x.nonzero() =" << std::endl;
std::cout << (x.nonzero()) << std::endl << std::endl;

std::cout << "<<< tensor.gather >>>" << std::endl;
std::cout << "注意，index tensor必须指明类型为int64" << std::endl;
torch::Tensor g = torch::ones({2,2}, torch::kInt64);
std::cout << (x.gather(0, g)) << std::endl << std::endl;
// std::cout << (torch::gather(x, 0, g, false)) << std::endl << std::endl;


x =
  0   1   2   3
  4   5   6   7
  8   9  10  11
[ CPUFloatType{3,4} ]

<<< tensor.index_select >>>
 1
 2
[ CPULongType{2} ]

x.index_select(dim = 0, index = idx) =
  4   5   6   7
  8   9  10  11
[ CPUFloatType{2,4} ]

x.index_select(dim = 1, index = idx) =
  1   2
  5   6
  9  10
[ CPUFloatType{3,2} ]

<<< tensor.masked_select >>>
 0  0  0  0
 0  0  1  1
 1  1  1  1
[ CPUBoolType{3,4} ]

x.masked_select(mask = mask) =
  6
  7
  8
  9
 10
 11
[ CPUFloatType{6} ]

<<< tensor.nonzero >>>
注意，返回值是非零元素下标，即x,y 
x.nonzero() =
 0  1
 0  2
 0  3
 1  0
 1  1
 1  2
 1  3
 2  0
 2  1
 2  2
 2  3
[ CPULongType{11,2} ]

<<< tensor.gather >>>
注意，index tensor必须指明类型为int64
 4  5
 4  5
[ CPUFloatType{2,2} ]



### 改变形状

In [36]:
/* *
 *  Change shapes
 */
torch::Tensor y = x.view({4, -1});
std::cout << "y =" << std::endl;
std::cout << (y) << std::endl << std::endl;

y =
  0   1   2
  3   4   5
  6   7   8
  9  10  11
[ CPUFloatType{4,3} ]

