In [1]:
#include "stdio.h"
#include "stdlib.h"
#include <iostream>

/*a workaround to solve cling issue*/
#include "../macos_cling_workaround.hpp"
/*set libtorch path, load libs*/
#include "../load_libtorch.hpp"
#include <torch/torch.h>

# 1.创建一个Tensor

创建未初始化的tensor：

In [2]:
torch::Tensor t1 = torch::empty(3, torch::kInt64);

std::cout << t1 << std::endl;

 7.3111e+18
 3.5543e+18
 8.0309e+18
[ CPULongType{3} ]


In [3]:
torch::Tensor t2 = torch::empty({5,6}, torch::kInt32);
std::cout << t2 << std::endl;

-5.7050e+08  2.1851e+04  0.0000e+00  0.0000e+00  9.0000e+00  1.2322e+09
 1.2634e+09  9.0921e+08  1.9531e+09  1.7687e+09  1.6013e+09  1.9537e+09
 8.7696e+08  1.7025e+09  1.9126e+09  1.5993e+09  1.6000e+02  0.0000e+00
 8.0000e+01  0.0000e+00 -5.6166e+08  2.1851e+04  0.0000e+00  0.0000e+00
 1.0000e+01  1.9524e+09  1.2634e+09  9.0921e+08  1.9531e+09  1.7687e+09
[ CPUIntType{5,6} ]


In [4]:
torch::Tensor t3 = torch::empty({3,4,2}, torch::kInt8);
std::cout << t3 << std::endl;

(1,.,.) = 
  101  102
  105  110
  101  100
   84  101

(2,.,.) = 
  110  115
  111  114
   73  109
  112  108

(3,.,.) = 
   69   69
   55  114
  101  116
   97  105
[ CPUCharType{3,4,2} ]


创建值为0的tensor：

In [5]:
torch::Tensor x = torch::zeros({3, 4});
std::cout << x << std::endl;

torch::Tensor y = torch::zeros({3, 4}, torch::kInt);
std::cout << y << std::endl;

 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUFloatType{3,4} ]
 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUIntType{3,4} ]


创建值为随机数的tensor：

In [6]:
torch::Tensor x = torch::rand({3, 4});
std::cout << x << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor y = torch::rand({3, 4}, torch::kFloat64);
std::cout << y << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor z = torch::randn({5, 3, 4}, torch::kFloat32);
std::cout << z << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 0.4444  0.7839  0.3972  0.5826
 0.8967  0.1082  0.5972  0.1979
 0.5112  0.3519  0.5890  0.8016
[ CPUFloatType{3,4} ]
<<<=========>>>

 0.3386  0.7420  0.4815  0.3888
 0.8127  0.1300  0.6292  0.4419
 0.7200  0.4255  0.8997  0.3681
[ CPUDoubleType{3,4} ]
<<<=========>>>

(1,.,.) = 
 -0.2787  1.2748  0.8307  0.9763
 -0.3594 -1.1021 -0.6364 -0.0364
  0.7180  0.0749 -0.0436 -2.4029

(2,.,.) = 
 -0.2440 -0.0459  0.8772 -0.9237
 -1.6146 -0.5144 -0.0731  0.2669
 -0.5208 -0.0864  0.9103  0.8287

(3,.,.) = 
 -0.8943 -1.7940  0.0125  1.6025
 -2.0548  0.3773  1.4870  0.5982
 -0.0344  0.8939  1.7970  0.5809

(4,.,.) = 
  1.1613 -1.6727 -1.1365  1.2555
 -0.1700  0.2928  1.7869 -0.2510
  0.2229  2.3172 -2.0089 -0.7028

(5,.,.) = 
 -0.1174 -0.4590 -0.6379  0.7281
  0.0454  0.5225 -0.3091  1.8815
  0.1755 -1.0258 -0.2639  0.5765
[ CPUFloatType{5,3,4} ]
<<<=========>>>



根据已有tensor创建新的tensor：

In [7]:
torch::Tensor t = torch::ones({3,3});
t += 2;


torch::Tensor a(t);
std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 3  3  3
 3  3  3
 3  3  3
[ CPUFloatType{3,3} ]
<<<=========>>>



In [8]:
torch::Tensor a = torch::ones({5,3});
a = torch::randn_like(a);

std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 0.1059  1.7008 -1.0940
 0.6755 -0.5386 -1.5082
 0.5866  0.4006  1.7089
-0.3359  0.1243 -0.2685
 1.2250 -1.8495  0.8217
[ CPUFloatType{5,3} ]
<<<=========>>>



# 2. Tensor的相关运算

## 加法运算

In [10]:
torch::Tensor x = torch::ones({5,3});
torch::Tensor y = torch::randn({5,3});

std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

std::cout << "y =" << std::endl;
std::cout << (y) << std::endl << std::endl;

std::cout << "x+y =" << std::endl;
std::cout << (x+y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "torch::add(x,y) =" << std::endl;
std::cout << torch::add(x,y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "y.add_(x) =" << std::endl;
std::cout << y.add_(x) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

x =
 1  1  1
 1  1  1
 1  1  1
 1  1  1
 1  1  1
[ CPUFloatType{5,3} ]

y =
-0.4262  0.2588 -1.2324
 1.5842 -1.4629  0.5925
-0.2029  0.6585 -0.0634
 2.2986 -0.6072  0.9584
 2.4718  1.3781  1.0643
[ CPUFloatType{5,3} ]

x+y =
 0.5738  1.2588 -0.2324
 2.5842 -0.4629  1.5925
 0.7971  1.6585  0.9366
 3.2986  0.3928  1.9584
 3.4718  2.3781  2.0643
[ CPUFloatType{5,3} ]
<<<=========>>>

torch::add(x,y) =
 0.5738  1.2588 -0.2324
 2.5842 -0.4629  1.5925
 0.7971  1.6585  0.9366
 3.2986  0.3928  1.9584
 3.4718  2.3781  2.0643
[ CPUFloatType{5,3} ]
<<<=========>>>

y.add_(x) =
 0.5738  1.2588 -0.2324
 2.5842 -0.4629  1.5925
 0.7971  1.6585  0.9366
 3.2986  0.3928  1.9584
 3.4718  2.3781  2.0643
[ CPUFloatType{5,3} ]
<<<=========>>>



## 索引
借助于torch::Tensor::index()和torch::Tensor::index_put_()函数，我们可以在libtorch中实现类似pytorch中对tensor的切片存取操作。具体说明详见[tensor_indexing](https://pytorch.org/cppdocs/notes/tensor_indexing.html)页面.

In [47]:
torch::Tensor x = torch::zeros({3,4});

for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 4; j++) {
        x[i][j] = i * 4 + j;
    }
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

/* *
 *  Getter ops
 */

std::cout << "(in python) x[None]=" << std::endl;
std::cout << (x.index({torch::indexing::None})) << std::endl << std::endl;


std::cout << "(in python) x[Ellipsis, ...]=" << std::endl;
std::cout << (x.index({torch::indexing::Ellipsis, "..."})) << std::endl << std::endl;


std::cout << "(in python) x[1,1]=" << std::endl;
std::cout << (x.index({1,1})) << std::endl << std::endl;


std::cout << "(in python) x[True, False]=" << std::endl;
std::cout << (x.index({true, false})) << std::endl << std::endl;


std::cout << "(in python) x[1::2]=" << std::endl;
std::cout << (x.index({torch::indexing::Slice(1, torch::indexing::None, 2)})) << std::endl << std::endl;

std::cout << "(in python) x[::2]=" << std::endl;
std::cout << (x.index({torch::indexing::Slice(torch::indexing::None, torch::indexing::None, 2)})) << std::endl << std::endl;



torch::Tensor y = x.view({2, -1});
std::cout << "y =" << std::endl;
std::cout << (y) << std::endl << std::endl;


x =
  0   1   2   3
  4   5   6   7
  8   9  10  11
[ CPUFloatType{3,4} ]

(in python) x[None]=
(1,.,.) = 
   0   1   2   3
   4   5   6   7
   8   9  10  11
[ CPUFloatType{1,3,4} ]

(in python) x[Ellipsis, ...]=
  0   1   2   3
  4   5   6   7
  8   9  10  11
[ CPUFloatType{3,4} ]

(in python) x[1,1]=
5
[ CPUFloatType{} ]

(in python) x[True, False]=
[ CPUFloatType{0,3,4} ]

(in python) x[1::2]=
 4  5  6  7
[ CPUFloatType{1,4} ]

(in python) x[::2]=
  0   1   2   3
  8   9  10  11
[ CPUFloatType{2,4} ]

y =
  0   1   2   3   4   5
  6   7   8   9  10  11
[ CPUFloatType{2,6} ]



# 3. 引申内容 - Part 1：PYTORCH C++ API的组成

截止到PyTorch 1.7.1版本，其C++ API由5大部分组成，如下表所示：

| 命名空间 | 功能描述  |
| :----: | :---- |
| **ATen**   | The foundational tensor and mathematical operation library on which all else is built. |
| **Autograd**   | Augments ATen with automatic differentiation. |
| **C++ Frontend**   | High level constructs for training and evaluation of machine learning models. |
| **TorchScript**   | An interface to the TorchScript JIT compiler and interpreter. |
| **C++ Extensions**   | A means of extending the Python API with custom C++ and CUDA routines. |


## ATen
ATen是一个基础的tensor库，PyTorch中Python和C++接口函数都是构建在这个库的基础上的。它提供了一个Tensor类，在这个类中定义了上百中tensor的相关操作，多数操作可以同时支持CPU和GPU实现，Tensor类可以根据数据类型来动态指定在哪种处理器上执行操作。其命名空间为at::。下面是个简单的例子：

In [10]:
#include <ATen/ATen.h>

at::Tensor a = at::ones({2, 2}, at::kInt);
std::cout << "a = " << std::endl << a << std::endl;
at::Tensor b = at::randn({2, 2}, at::kFloat);
std::cout << "b = " << std::endl << b << std::endl;
auto c = a + b.to(at::kInt);
std::cout << "c = " << std::endl << c << std::endl;


a = 
 1  1
 1  1
[ CPUIntType{2,2} ]
b = 
 0.1778 -0.3870
-3.1225 -0.3888
[ CPUFloatType{2,2} ]
c = 
 1  1
-2  1
[ CPUIntType{2,2} ]


## Autograd
autograd是PyTorch C++ API的一部分，属于对ATen的Tensor类的功能增强，使其具备自动化微分功能。autograd系统会记录tensor上的操作，进而形成一个autograd graph。调用tensor变量的backwards()函数会产生逆向的差分运算。
注意：ATen中的at::Tensor类默认并不具备微分功能。为了使tensors具备可微分功能，你必须使用tensor的工厂方法，即调用torch::命名空间的函数，而不是去直接调用at::命名空间的函数。比如，at::ones()函数产生的tensor是不具备可微分功能的，但是torch::ones()函数的就可以。

## C++ Frontend
PyTorch C++前端框架为神经网络和通用机器学习提供了一套纯C++的模型接口，包括：
* 用于自定义机器学习模型的层级模型接口系统；
* 为构建深度学习模型的常见函数库，如卷积运算，RNN，BN等；
* 深度学习优化方法API，如SGD,Adam,RMSprop等；
* 一种数据集和数据管道的表示方式；
* 序列化存储和加载训练过程中checkpoints的格式；
* 在多GPU上并行运行模型；
* TorchScript JIT compiler的接入口；

## TorchScript
这是对PyTorch模型的一种表示方法。事实上，TorchScript在某种意义上是一种编程语言，是Python的一个子集。TorchScript的C++接口包含的主要功能有：
* 加载和运行序列化TorchScript模型；
* 提供相关API，使用户可以自定义算子；
* TorchScript C++程序的即时编译；

对于第一个功能而言，这个给用户提供了一种方法，即开发者可以使用python来编写算法并训练，训练得到的模型参数可以直接用于C++程序中，而无需使用libtorch重新编写深度学习模型并从头训练。（听着不错，但实测发现有某种程度的精度损失）。

## C++ Extensions
C++扩展提供了一种简单而有效的方法，使得开发者可以方便的访问PyTorch的上层接口。其最常见的用法是让开发者可以自定义算子。