In [1]:
#include "stdio.h"
#include "stdlib.h"
#include <iostream>

/*a workaround to solve cling issue*/
#include "../macos_cling_workaround.hpp"
/*set libtorch path, load libs*/
#include "../load_libtorch.hpp"
#include <torch/torch.h>

# 1.创建一个Tensor

创建未初始化的tensor：

In [2]:
torch::Tensor t1 = torch::empty(3, torch::kInt64);

std::cout << t1 << std::endl;

 8.3140e+18
 5.9943e+18
 8.1046e+18
[ CPULongType{3} ]


In [3]:
torch::Tensor t2 = torch::empty({5,6}, torch::kInt32);
std::cout << t2 << std::endl;

      4   32698       0  262147 -1.59227e+09   32698
-1.59227e+09   32698 -1.59433e+09   32698 -1.59227e+09   32698
      1       0 -1.59396e+09   32698       3   32698
-1.59226e+09   32698       0 -1.61061e+09 -1.44183e+09 -1.07374e+09
-1.59233e+09   32698       1       0       2       0
[ CPUIntType{5,6} ]


In [4]:
torch::Tensor t3 = torch::empty({3,4,2}, torch::kInt8);
std::cout << t3 << std::endl;

(1,.,.) = 
   95   46
   95   90
   78   53
  116  111

(2,.,.) = 
  114   99
  104   56
   97  117
  116  111

(3,.,.) = 
  103  114
   97  100
   49   50
   65  117
[ CPUCharType{3,4,2} ]


创建值为0的tensor：

In [5]:
torch::Tensor x = torch::zeros({3, 4});
std::cout << x << std::endl;

torch::Tensor y = torch::zeros({3, 4}, torch::kInt);
std::cout << y << std::endl;

 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUFloatType{3,4} ]
 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUIntType{3,4} ]


创建值为随机数的tensor：

In [6]:
torch::Tensor x = torch::rand({3, 4});
std::cout << x << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor y = torch::rand({3, 4}, torch::kFloat64);
std::cout << y << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor z = torch::randn({5, 3, 4}, torch::kFloat32);
std::cout << z << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 0.9316  0.3603  0.4244  0.7145
 0.3084  0.1115  0.0910  0.3234
 0.1561  0.4228  0.1366  0.3448
[ CPUFloatType{3,4} ]
<<<=========>>>

 0.1364  0.4437  0.4620  0.7042
 0.7517  0.7092  0.7386  0.1038
 0.4672  0.4118  0.0354  0.0548
[ CPUDoubleType{3,4} ]
<<<=========>>>

(1,.,.) = 
  0.3148  0.0204  1.8046  0.3619
  0.7671  0.9303 -0.5180  1.0040
 -0.6480 -0.7978  1.2555 -0.9101

(2,.,.) = 
  1.3373  0.5215  1.1415 -1.7563
  0.5426 -0.1113  0.0532 -0.2123
 -1.4324 -0.7755  0.6674  0.1890

(3,.,.) = 
  1.2514  1.4398 -0.4136 -0.7535
  0.5899 -0.1638  1.2922 -1.1142
  0.4097  0.4343  1.0103 -1.2200

(4,.,.) = 
 -0.5092 -0.2616 -1.7434 -0.2984
 -1.1092 -1.8602 -0.2111  1.1354
  2.7976  0.6200 -1.5034  0.2607

(5,.,.) = 
  0.4729 -0.4211 -1.4476  0.2703
 -1.7286 -0.6216  1.8239 -2.0770
 -2.3602  0.3061 -2.9025  0.1346
[ CPUFloatType{5,3,4} ]
<<<=========>>>



根据已有tensor创建新的tensor：

In [7]:
torch::Tensor t = torch::ones({3,3});
t += 2;


torch::Tensor a(t);
std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 3  3  3
 3  3  3
 3  3  3
[ CPUFloatType{3,3} ]
<<<=========>>>



In [8]:
torch::Tensor a = torch::ones({5,3});
a = torch::randn_like(a);

std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 2.5154 -0.3320 -0.2869
 0.2237 -1.8562 -0.3705
-0.7760  1.2093 -0.3157
 1.0249 -0.4432  0.1899
 0.4012 -0.5514  0.4836
[ CPUFloatType{5,3} ]
<<<=========>>>



# 2. Tensor的相关运算

## 2.1 加法运算

In [19]:
torch::Tensor x = torch::ones({5,3});
torch::Tensor y = torch::randn({5,3});

std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

std::cout << "y =" << std::endl;
std::cout << (y) << std::endl << std::endl;

std::cout << "x+y =" << std::endl;
std::cout << (x+y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "torch::add(x,y) =" << std::endl;
std::cout << torch::add(x,y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "y.add_(x) =" << std::endl;
std::cout << y.add_(x) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

x =
 1  1  1
 1  1  1
 1  1  1
 1  1  1
 1  1  1
[ CPUFloatType{5,3} ]

y =
-0.4342  0.4025 -1.1347
-0.6327 -0.9811  0.0020
-0.0682 -0.9280  0.3189
 2.7281  0.6704 -0.6495
 0.2655 -1.3120 -1.3697
[ CPUFloatType{5,3} ]

x+y =
 0.5658  1.4025 -0.1347
 0.3673  0.0189  1.0020
 0.9318  0.0720  1.3189
 3.7281  1.6704  0.3505
 1.2655 -0.3120 -0.3697
[ CPUFloatType{5,3} ]
<<<=========>>>

torch::add(x,y) =
 0.5658  1.4025 -0.1347
 0.3673  0.0189  1.0020
 0.9318  0.0720  1.3189
 3.7281  1.6704  0.3505
 1.2655 -0.3120 -0.3697
[ CPUFloatType{5,3} ]
<<<=========>>>

y.add_(x) =
 0.5658  1.4025 -0.1347
 0.3673  0.0189  1.0020
 0.9318  0.0720  1.3189
 3.7281  1.6704  0.3505
 1.2655 -0.3120 -0.3697
[ CPUFloatType{5,3} ]
<<<=========>>>



# 3. 引申内容 - Part 1：PYTORCH C++ API的组成

截止到PyTorch 1.7.1版本，其C++ API由5大部分组成，如下表所示：

| 命名空间 | 功能描述  |
| :----: | :---- |
| **ATen**   | The foundational tensor and mathematical operation library on which all else is built. |
| **Autograd**   | Augments ATen with automatic differentiation. |
| **C++ Frontend**   | High level constructs for training and evaluation of machine learning models. |
| **TorchScript**   | An interface to the TorchScript JIT compiler and interpreter. |
| **C++ Extensions**   | A means of extending the Python API with custom C++ and CUDA routines. |


## ATen
ATen是一个基础的tensor库，PyTorch中Python和C++接口函数都是构建在这个库的基础上的。它提供了一个Tensor类，在这个类中定义了上百中tensor的相关操作，多数操作可以同时支持CPU和GPU实现，Tensor类可以根据数据类型来动态指定在哪种处理器上执行操作。其命名空间为at::。下面是个简单的例子：

In [10]:
#include <ATen/ATen.h>

at::Tensor a = at::ones({2, 2}, at::kInt);
std::cout << "a = " << std::endl << a << std::endl;
at::Tensor b = at::randn({2, 2}, at::kFloat);
std::cout << "b = " << std::endl << b << std::endl;
auto c = a + b.to(at::kInt);
std::cout << "c = " << std::endl << c << std::endl;


a = 
 1  1
 1  1
[ CPUIntType{2,2} ]
b = 
 0.1778 -0.3870
-3.1225 -0.3888
[ CPUFloatType{2,2} ]
c = 
 1  1
-2  1
[ CPUIntType{2,2} ]


## Autograd
autograd是PyTorch C++ API的一部分，属于对ATen的Tensor类的功能增强，使其具备自动化微分功能。autograd系统会记录tensor上的操作，进而形成一个autograd graph。调用tensor变量的backwards()函数会产生逆向的差分运算。
注意：ATen中的at::Tensor类默认并不具备微分功能。为了使tensors具备可微分功能，你必须使用tensor的工厂方法，即调用torch::命名空间的函数，而不是去直接调用at::命名空间的函数。比如，at::ones()函数产生的tensor是不具备可微分功能的，但是torch::ones()函数的就可以。

## C++ Frontend
PyTorch C++前端框架为神经网络和通用机器学习提供了一套纯C++的模型接口，包括：
* 用于自定义机器学习模型的层级模型接口系统；
* 为构建深度学习模型的常见函数库，如卷积运算，RNN，BN等；
* 深度学习优化方法API，如SGD,Adam,RMSprop等；
* 一种数据集和数据管道的表示方式；
* 序列化存储和加载训练过程中checkpoints的格式；
* 在多GPU上并行运行模型；
* TorchScript JIT compiler的接入口；

## TorchScript
这是对PyTorch模型的一种表示方法。事实上，TorchScript在某种意义上是一种编程语言，是Python的一个子集。TorchScript的C++接口包含的主要功能有：
* 加载和运行序列化TorchScript模型；
* 提供相关API，使用户可以自定义算子；
* TorchScript C++程序的即时编译；

对于第一个功能而言，这个给用户提供了一种方法，即开发者可以使用python来编写算法并训练，训练得到的模型参数可以直接用于C++程序中，而无需使用libtorch重新编写深度学习模型并从头训练。（听着不错，但实测发现有某种程度的精度损失）。

## C++ Extensions
C++扩展提供了一种简单而有效的方法，使得开发者可以方便的访问PyTorch的上层接口。其最常见的用法是让开发者可以自定义算子。